
import java.awt.Color;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Techno Service
 */
public class carMove extends JFrame {

    /**
     * Creates new form board
     */
    public carMove() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JLabel();
        car = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        camera = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JLabel();
        fix = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        feul = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        car1 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        //getContentPane().setBackground(Color.BLUE);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(100, 120));
        setPreferredSize(new java.awt.Dimension(400, 510));
        setResizable(false);
        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
       
        
        

        getLayeredPane().add(car);
        car.setBounds(220, 410, 40, 70);
        car.setIcon(new javax.swing.ImageIcon(getClass().getResource("mycar.png")));
        
        
        getLayeredPane().add(car1);
        car1.setBounds(220, 10, 40, 70);
        car1.setIcon(new javax.swing.ImageIcon(getClass().getResource("othercar.png")));
        
        
        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        getLayeredPane().add(jPanel1);
        jPanel1.setBounds(58, 0, 250, 480);
        jPanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("street_2.png")));
        //car.setBackground(new java.awt.Color(255, 0, 0));

        
        
        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        getLayeredPane().add(jPanel2);
        jPanel2.setBounds(290, 0, 1, 480);

        jLabel1.setText("1000");
        getLayeredPane().add(jLabel1);
        jLabel1.setBounds(2, 40, 70, 20);

        jLabel2.setText("0");
        getLayeredPane().add(jLabel2);
        jLabel2.setBounds(2, 440, 70, 20);

        jLabel3.setText("500");
        getLayeredPane().add(jLabel3);
        jLabel3.setBounds(2, 220, 70, 20);

        camera.setBackground(new java.awt.Color(255, 0, 153));
        camera.setName(""); // NOI18N
        camera.setLayout(null);
        
        
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Camera");
        camera.add(jLabel4);
        jLabel4.setBounds(10, 10, 50, 17);
        getLayeredPane().add(camera);
        camera.setBounds(310, 10, 70, 40);
        camera.setVisible(false);
        
        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );

        getLayeredPane().add(jPanel3);
        jPanel3.setBounds(58, 0, 1, 485);

        fix.setBackground(new java.awt.Color(0, 153, 0));
        fix.setName(""); // NOI18N
        fix.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Repair");
        fix.add(jLabel5);
        jLabel5.setBounds(17, 27, 50, 17);

        getLayeredPane().add(fix);
        fix.setBounds(310, 60, 70, 70);
        fix.setVisible(false);
        feul.setBackground(new java.awt.Color(255, 255, 0));
        feul.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Feul");
        feul.add(jLabel6);
        jLabel6.setBounds(20, 27, 50, 17);

        getLayeredPane().add(feul);
        feul.setBounds(310, 140, 70, 70);
        feul.setVisible(false);
        
        
        
        pack();
    }// </editor-fold>                        
    private void formKeyPressed(java.awt.event.KeyEvent evt) {                                
        int x=evt.getExtendedKeyCode();
        System.out.println(x);
        if(x==32){
            Tester.cva.setAcceleration(-1*Tester.cva.getMaxBrakeAcceleration());
        }else if (x==37){
            carMove.car.setBounds(105, 410, 40, 70);
            Tester.curreve_line=2;
        }else if (x==39){
            carMove.car.setBounds(220, 410, 40, 70);
            Tester.curreve_line=1;
        }else if (x==38){
            Tester.cva.setAcceleration(Tester.cva.getAcceleration()+2);
        }
    }    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new board().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify   
    static javax.swing.JLabel back;
    static javax.swing.JPanel camera;
    static javax.swing.JLabel car;
    static javax.swing.JLabel car1;
    static javax.swing.JPanel feul;
    static javax.swing.JPanel fix;
    static javax.swing.JLabel jLabel1;
    static javax.swing.JLabel jLabel2;
    static javax.swing.JLabel jLabel3;
    static javax.swing.JLabel jLabel4;
    static javax.swing.JLabel jLabel5;
    static javax.swing.JLabel jLabel6;
    static javax.swing.JLabel jPanel1;
    static javax.swing.JLabel jPanel2;
    static javax.swing.JLabel jPanel3;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration                   
}
